import { Company } from './db';

// Curated list of 120+ Dutch companies ideal for Versis lead generation
// Mix of enterprise, government, and tech companies
export const seedCompanies: Omit<Company, 'id' | 'lead_score' | 'created_at' | 'updated_at'>[] = [
  // GOVERNMENT / PUBLIC SECTOR (High Value)
  { name: 'Rijkswaterstaat', sector: 'Overheid', size: 'enterprise', employee_count: 9000, city: 'Utrecht', province: 'Utrecht', is_government: true, is_enterprise: true, description: 'Uitvoeringsorganisatie van het Ministerie van I&W', website: 'rijkswaterstaat.nl', status: 'new' },
  { name: 'Belastingdienst', sector: 'Overheid', size: 'enterprise', employee_count: 28000, city: 'Den Haag', province: 'Zuid-Holland', is_government: true, is_enterprise: true, description: 'Nederlandse belastingautoriteit', website: 'belastingdienst.nl', status: 'new' },
  { name: 'Gemeente Amsterdam', sector: 'Overheid', size: 'enterprise', employee_count: 18000, city: 'Amsterdam', province: 'Noord-Holland', is_government: true, is_enterprise: true, description: 'Grootste gemeente van Nederland', website: 'amsterdam.nl', status: 'new' },
  { name: 'Gemeente Rotterdam', sector: 'Overheid', size: 'enterprise', employee_count: 14000, city: 'Rotterdam', province: 'Zuid-Holland', is_government: true, is_enterprise: true, description: 'Tweede stad van Nederland', website: 'rotterdam.nl', status: 'new' },
  { name: 'Gemeente Den Haag', sector: 'Overheid', size: 'enterprise', employee_count: 11000, city: 'Den Haag', province: 'Zuid-Holland', is_government: true, is_enterprise: true, description: 'Regeringszetel van Nederland', website: 'denhaag.nl', status: 'new' },
  { name: 'Gemeente Utrecht', sector: 'Overheid', size: 'large', employee_count: 4500, city: 'Utrecht', province: 'Utrecht', is_government: true, is_enterprise: true, description: 'Vierde stad van Nederland', website: 'utrecht.nl', status: 'new' },
  { name: 'Provincie Noord-Holland', sector: 'Overheid', size: 'large', employee_count: 1500, city: 'Haarlem', province: 'Noord-Holland', is_government: true, is_enterprise: true, description: 'Provinciale overheid', website: 'noord-holland.nl', status: 'new' },
  { name: 'Provincie Zuid-Holland', sector: 'Overheid', size: 'large', employee_count: 1800, city: 'Den Haag', province: 'Zuid-Holland', is_government: true, is_enterprise: true, description: 'Provinciale overheid', website: 'zuid-holland.nl', status: 'new' },
  { name: 'UWV', sector: 'Overheid', size: 'enterprise', employee_count: 20000, city: 'Amsterdam', province: 'Noord-Holland', is_government: true, is_enterprise: true, description: 'Uitkeringsinstituut werknemersverzekeringen', website: 'uwv.nl', status: 'new' },
  { name: 'RDW', sector: 'Overheid', size: 'large', employee_count: 1500, city: 'Zoetermeer', province: 'Zuid-Holland', is_government: true, is_enterprise: true, description: 'Rijksdienst voor het Wegverkeer', website: 'rdw.nl', status: 'new' },
  { name: 'Kadaster', sector: 'Overheid', size: 'large', employee_count: 2100, city: 'Apeldoorn', province: 'Gelderland', is_government: true, is_enterprise: true, description: 'Register voor vastgoed en grond', website: 'kadaster.nl', status: 'new' },
  { name: 'RIVM', sector: 'Overheid', size: 'large', employee_count: 2000, city: 'Bilthoven', province: 'Utrecht', is_government: true, is_tech: true, description: 'Rijksinstituut voor Volksgezondheid en Milieu', website: 'rivm.nl', status: 'new' },
  { name: 'CBS', sector: 'Overheid', size: 'large', employee_count: 2000, city: 'Den Haag', province: 'Zuid-Holland', is_government: true, is_tech: true, description: 'Centraal Bureau voor de Statistiek', website: 'cbs.nl', status: 'new' },
  { name: 'Politie Nederland', sector: 'Overheid', size: 'enterprise', employee_count: 65000, city: 'Den Haag', province: 'Zuid-Holland', is_government: true, is_enterprise: true, description: 'Nationale politiekorps', website: 'politie.nl', status: 'new' },
  { name: 'Defensie', sector: 'Overheid', size: 'enterprise', employee_count: 60000, city: 'Den Haag', province: 'Zuid-Holland', is_government: true, is_enterprise: true, description: 'Ministerie van Defensie', website: 'defensie.nl', status: 'new' },

  // FINANCIAL SERVICES
  { name: 'ING Bank', sector: 'Financiële dienstverlening', size: 'enterprise', employee_count: 57000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_tech: true, description: 'Internationale bank', website: 'ing.nl', status: 'new' },
  { name: 'Rabobank', sector: 'Financiële dienstverlening', size: 'enterprise', employee_count: 43000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, is_tech: true, description: 'Coöperatieve bank', website: 'rabobank.nl', status: 'new' },
  { name: 'ABN AMRO', sector: 'Financiële dienstverlening', size: 'enterprise', employee_count: 21000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_tech: true, description: 'Nederlandse bank', website: 'abnamro.nl', status: 'new' },
  { name: 'Achmea', sector: 'Financiële dienstverlening', size: 'enterprise', employee_count: 14000, city: 'Zeist', province: 'Utrecht', is_enterprise: true, description: 'Grootste verzekeraar van Nederland', website: 'achmea.nl', status: 'new' },
  { name: 'Nationale-Nederlanden', sector: 'Financiële dienstverlening', size: 'enterprise', employee_count: 8000, city: 'Den Haag', province: 'Zuid-Holland', is_enterprise: true, description: 'Verzekeraar en pensioenuitvoerder', website: 'nn.nl', status: 'new' },
  { name: 'Aegon', sector: 'Financiële dienstverlening', size: 'enterprise', employee_count: 5000, city: 'Den Haag', province: 'Zuid-Holland', is_enterprise: true, description: 'Internationale verzekeringsmaatschappij', website: 'aegon.nl', status: 'new' },
  { name: 'De Nederlandsche Bank', sector: 'Financiële dienstverlening', size: 'large', employee_count: 2000, city: 'Amsterdam', province: 'Noord-Holland', is_government: true, is_enterprise: true, description: 'Centrale bank van Nederland', website: 'dnb.nl', status: 'new' },
  { name: 'APG', sector: 'Financiële dienstverlening', size: 'large', employee_count: 3000, city: 'Heerlen', province: 'Limburg', is_enterprise: true, description: 'Grootste pensioenuitvoerder', website: 'apg.nl', status: 'new' },
  { name: 'Centraal Beheer', sector: 'Financiële dienstverlening', size: 'large', employee_count: 3500, city: 'Apeldoorn', province: 'Gelderland', is_enterprise: true, description: 'Verzekeraar (onderdeel Achmea)', website: 'centraalbeheer.nl', status: 'new' },
  { name: 'PGGM', sector: 'Financiële dienstverlening', size: 'large', employee_count: 1500, city: 'Zeist', province: 'Utrecht', is_enterprise: true, description: 'Pensioenuitvoerder zorgsector', website: 'pggm.nl', status: 'new' },

  // ICT & TECHNOLOGY
  { name: 'ASML', sector: 'ICT & Technologie', size: 'enterprise', employee_count: 42000, city: 'Veldhoven', province: 'Noord-Brabant', is_enterprise: true, is_tech: true, description: 'Chipproductie machines', website: 'asml.com', status: 'new' },
  { name: 'Philips', sector: 'ICT & Technologie', size: 'enterprise', employee_count: 77000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_tech: true, description: 'Gezondheidstechnologie', website: 'philips.nl', status: 'new' },
  { name: 'NXP Semiconductors', sector: 'ICT & Technologie', size: 'enterprise', employee_count: 34000, city: 'Eindhoven', province: 'Noord-Brabant', is_enterprise: true, is_tech: true, description: 'Halfgeleider fabrikant', website: 'nxp.com', status: 'new' },
  { name: 'Booking.com', sector: 'ICT & Technologie', size: 'enterprise', employee_count: 17000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_tech: true, description: 'Online reisplatform', website: 'booking.com', status: 'new' },
  { name: 'Adyen', sector: 'ICT & Technologie', size: 'large', employee_count: 4000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_tech: true, description: 'Betalingsplatform', website: 'adyen.com', status: 'new' },
  { name: 'Bol.com', sector: 'ICT & Technologie', size: 'large', employee_count: 3000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, is_tech: true, description: 'Grootste webwinkel van NL/BE', website: 'bol.com', status: 'new' },
  { name: 'Coolblue', sector: 'ICT & Technologie', size: 'large', employee_count: 5000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, is_tech: true, description: 'Webwinkel en retailer', website: 'coolblue.nl', status: 'new' },
  { name: 'TomTom', sector: 'ICT & Technologie', size: 'large', employee_count: 4000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_tech: true, description: 'Navigatie en kaarten', website: 'tomtom.com', status: 'new' },
  { name: 'Ordina', sector: 'ICT & Technologie', size: 'large', employee_count: 3000, city: 'Nieuwegein', province: 'Utrecht', is_tech: true, description: 'IT-dienstverlener Benelux', website: 'ordina.nl', status: 'new' },
  { name: 'Capgemini Nederland', sector: 'ICT & Technologie', size: 'enterprise', employee_count: 7000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, is_tech: true, description: 'IT-consultancy', website: 'capgemini.com/nl', status: 'new' },
  { name: 'Cognizant NL', sector: 'ICT & Technologie', size: 'large', employee_count: 2000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_tech: true, description: 'IT-services', website: 'cognizant.com', status: 'new' },
  { name: 'Atos Nederland', sector: 'ICT & Technologie', size: 'large', employee_count: 4500, city: 'Amstelveen', province: 'Noord-Holland', is_enterprise: true, is_tech: true, description: 'IT-dienstverlener', website: 'atos.net', status: 'new' },
  { name: 'CGI Nederland', sector: 'ICT & Technologie', size: 'large', employee_count: 3000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, is_tech: true, description: 'IT en business consulting', website: 'cgi.com/nl', status: 'new' },
  { name: 'Conclusion', sector: 'ICT & Technologie', size: 'large', employee_count: 2000, city: 'Utrecht', province: 'Utrecht', is_tech: true, description: 'IT-dienstverlener', website: 'conclusion.nl', status: 'new' },
  { name: 'Centric', sector: 'ICT & Technologie', size: 'large', employee_count: 4000, city: 'Gouda', province: 'Zuid-Holland', is_tech: true, description: 'IT-oplossingen overheid', website: 'centric.eu', status: 'new' },

  // HEALTHCARE
  { name: 'Erasmus MC', sector: 'Gezondheidszorg', size: 'enterprise', employee_count: 17000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Universitair Medisch Centrum', website: 'erasmusmc.nl', status: 'new' },
  { name: 'Amsterdam UMC', sector: 'Gezondheidszorg', size: 'enterprise', employee_count: 15000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Universitair Medisch Centrum', website: 'amsterdamumc.nl', status: 'new' },
  { name: 'Radboudumc', sector: 'Gezondheidszorg', size: 'enterprise', employee_count: 12000, city: 'Nijmegen', province: 'Gelderland', is_enterprise: true, description: 'Universitair Medisch Centrum', website: 'radboudumc.nl', status: 'new' },
  { name: 'UMC Utrecht', sector: 'Gezondheidszorg', size: 'enterprise', employee_count: 12000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, description: 'Universitair Medisch Centrum', website: 'umcutrecht.nl', status: 'new' },
  { name: 'LUMC', sector: 'Gezondheidszorg', size: 'enterprise', employee_count: 9000, city: 'Leiden', province: 'Zuid-Holland', is_enterprise: true, description: 'Leids Universitair MC', website: 'lumc.nl', status: 'new' },
  { name: 'UMCG', sector: 'Gezondheidszorg', size: 'enterprise', employee_count: 12000, city: 'Groningen', province: 'Groningen', is_enterprise: true, description: 'Universitair MC Groningen', website: 'umcg.nl', status: 'new' },
  { name: 'Maastricht UMC+', sector: 'Gezondheidszorg', size: 'large', employee_count: 7000, city: 'Maastricht', province: 'Limburg', is_enterprise: true, description: 'Universitair Medisch Centrum', website: 'mumc.nl', status: 'new' },
  { name: 'Rijnstate', sector: 'Gezondheidszorg', size: 'large', employee_count: 5000, city: 'Arnhem', province: 'Gelderland', is_enterprise: true, description: 'Topklinisch ziekenhuis', website: 'rijnstate.nl', status: 'new' },
  { name: 'Catharina Ziekenhuis', sector: 'Gezondheidszorg', size: 'large', employee_count: 4000, city: 'Eindhoven', province: 'Noord-Brabant', is_enterprise: true, description: 'Topklinisch ziekenhuis', website: 'catharinaziekenhuis.nl', status: 'new' },
  { name: 'Isala', sector: 'Gezondheidszorg', size: 'large', employee_count: 5500, city: 'Zwolle', province: 'Overijssel', is_enterprise: true, description: 'Topklinisch ziekenhuis', website: 'isala.nl', status: 'new' },

  // ENERGY & UTILITIES
  { name: 'Shell Nederland', sector: 'Energie & Utilities', size: 'enterprise', employee_count: 9000, city: 'Den Haag', province: 'Zuid-Holland', is_enterprise: true, description: 'Energie- en petrochemiebedrijf', website: 'shell.nl', status: 'new' },
  { name: 'TenneT', sector: 'Energie & Utilities', size: 'large', employee_count: 6000, city: 'Arnhem', province: 'Gelderland', is_enterprise: true, is_government: true, description: 'Beheerder hoogspanningsnet', website: 'tennet.eu', status: 'new' },
  { name: 'Eneco', sector: 'Energie & Utilities', size: 'large', employee_count: 3000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Energieleverancier', website: 'eneco.nl', status: 'new' },
  { name: 'Vattenfall Nederland', sector: 'Energie & Utilities', size: 'large', employee_count: 3500, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Energieleverancier', website: 'vattenfall.nl', status: 'new' },
  { name: 'Essent', sector: 'Energie & Utilities', size: 'large', employee_count: 2500, city: 'Den Bosch', province: 'Noord-Brabant', is_enterprise: true, description: 'Energieleverancier', website: 'essent.nl', status: 'new' },
  { name: 'Gasunie', sector: 'Energie & Utilities', size: 'large', employee_count: 2000, city: 'Groningen', province: 'Groningen', is_enterprise: true, is_government: true, description: 'Gasinfrastructuur', website: 'gasunie.nl', status: 'new' },
  { name: 'Alliander', sector: 'Energie & Utilities', size: 'large', employee_count: 7500, city: 'Arnhem', province: 'Gelderland', is_enterprise: true, description: 'Netwerkbeheerder', website: 'alliander.com', status: 'new' },
  { name: 'Stedin', sector: 'Energie & Utilities', size: 'large', employee_count: 4500, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Netwerkbeheerder', website: 'stedin.net', status: 'new' },
  { name: 'Vitens', sector: 'Energie & Utilities', size: 'large', employee_count: 1500, city: 'Zwolle', province: 'Overijssel', is_enterprise: true, description: 'Waterleidingbedrijf', website: 'vitens.nl', status: 'new' },
  { name: 'Waternet', sector: 'Energie & Utilities', size: 'large', employee_count: 2000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_government: true, description: 'Watercyclus Amsterdam', website: 'waternet.nl', status: 'new' },

  // TRANSPORT & LOGISTICS
  { name: 'NS (Nederlandse Spoorwegen)', sector: 'Transport & Logistiek', size: 'enterprise', employee_count: 21000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, is_government: true, description: 'Personenvervoer per spoor', website: 'ns.nl', status: 'new' },
  { name: 'ProRail', sector: 'Transport & Logistiek', size: 'large', employee_count: 5000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, is_government: true, description: 'Spoorweginfrastructuur', website: 'prorail.nl', status: 'new' },
  { name: 'Schiphol Group', sector: 'Transport & Logistiek', size: 'large', employee_count: 3500, city: 'Schiphol', province: 'Noord-Holland', is_enterprise: true, is_government: true, description: 'Luchthaven exploitant', website: 'schiphol.nl', status: 'new' },
  { name: 'KLM Royal Dutch Airlines', sector: 'Transport & Logistiek', size: 'enterprise', employee_count: 33000, city: 'Amstelveen', province: 'Noord-Holland', is_enterprise: true, description: 'Luchtvaartmaatschappij', website: 'klm.nl', status: 'new' },
  { name: 'Havenbedrijf Rotterdam', sector: 'Transport & Logistiek', size: 'large', employee_count: 1200, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, is_government: true, description: 'Grootste haven van Europa', website: 'portofrotterdam.com', status: 'new' },
  { name: 'PostNL', sector: 'Transport & Logistiek', size: 'enterprise', employee_count: 35000, city: 'Den Haag', province: 'Zuid-Holland', is_enterprise: true, description: 'Post- en pakketbezorging', website: 'postnl.nl', status: 'new' },
  { name: 'DHL Netherlands', sector: 'Transport & Logistiek', size: 'large', employee_count: 4000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, description: 'Express en logistiek', website: 'dhl.nl', status: 'new' },
  { name: 'GVB', sector: 'Transport & Logistiek', size: 'large', employee_count: 4500, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_government: true, description: 'Openbaar vervoer Amsterdam', website: 'gvb.nl', status: 'new' },
  { name: 'RET', sector: 'Transport & Logistiek', size: 'large', employee_count: 3000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, is_government: true, description: 'Openbaar vervoer Rotterdam', website: 'ret.nl', status: 'new' },
  { name: 'HTM', sector: 'Transport & Logistiek', size: 'large', employee_count: 2500, city: 'Den Haag', province: 'Zuid-Holland', is_enterprise: true, is_government: true, description: 'Openbaar vervoer Den Haag', website: 'htm.nl', status: 'new' },

  // INDUSTRY & MANUFACTURING
  { name: 'Tata Steel Nederland', sector: 'Industrie & Productie', size: 'enterprise', employee_count: 9000, city: 'IJmuiden', province: 'Noord-Holland', is_enterprise: true, description: 'Staalproducent', website: 'tatasteeleurope.com', status: 'new' },
  { name: 'DSM', sector: 'Industrie & Productie', size: 'enterprise', employee_count: 8000, city: 'Heerlen', province: 'Limburg', is_enterprise: true, is_tech: true, description: 'Life sciences en materialen', website: 'dsm.com', status: 'new' },
  { name: 'AkzoNobel', sector: 'Industrie & Productie', size: 'enterprise', employee_count: 5000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Verven en coatings', website: 'akzonobel.com', status: 'new' },
  { name: 'DAF Trucks', sector: 'Industrie & Productie', size: 'large', employee_count: 10000, city: 'Eindhoven', province: 'Noord-Brabant', is_enterprise: true, description: 'Vrachtwagenfabrikant', website: 'daf.com', status: 'new' },
  { name: 'VDL Groep', sector: 'Industrie & Productie', size: 'large', employee_count: 16000, city: 'Eindhoven', province: 'Noord-Brabant', is_enterprise: true, description: 'Industrieel concern', website: 'vdlgroep.com', status: 'new' },
  { name: 'Vanderlande', sector: 'Industrie & Productie', size: 'large', employee_count: 8000, city: 'Veghel', province: 'Noord-Brabant', is_enterprise: true, is_tech: true, description: 'Logistieke automatisering', website: 'vanderlande.com', status: 'new' },
  { name: 'Damen Shipyards', sector: 'Industrie & Productie', size: 'large', employee_count: 6000, city: 'Gorinchem', province: 'Zuid-Holland', is_enterprise: true, description: 'Scheepsbouw', website: 'damen.com', status: 'new' },
  { name: 'FrieslandCampina', sector: 'Industrie & Productie', size: 'enterprise', employee_count: 23000, city: 'Amersfoort', province: 'Utrecht', is_enterprise: true, description: 'Zuivelcoöperatie', website: 'frieslandcampina.com', status: 'new' },
  { name: 'Heineken Nederland', sector: 'Industrie & Productie', size: 'large', employee_count: 3000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Brouwerij', website: 'heineken.nl', status: 'new' },
  { name: 'Unilever Nederland', sector: 'Industrie & Productie', size: 'large', employee_count: 3000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Consumentengoederen', website: 'unilever.nl', status: 'new' },

  // BUSINESS SERVICES
  { name: 'Deloitte Nederland', sector: 'Zakelijke dienstverlening', size: 'large', employee_count: 7000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Accountancy en advies', website: 'deloitte.nl', status: 'new' },
  { name: 'PwC Nederland', sector: 'Zakelijke dienstverlening', size: 'large', employee_count: 5500, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Accountancy en advies', website: 'pwc.nl', status: 'new' },
  { name: 'EY Nederland', sector: 'Zakelijke dienstverlening', size: 'large', employee_count: 5000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Accountancy en advies', website: 'ey.com/nl', status: 'new' },
  { name: 'KPMG Nederland', sector: 'Zakelijke dienstverlening', size: 'large', employee_count: 4500, city: 'Amstelveen', province: 'Noord-Holland', is_enterprise: true, description: 'Accountancy en advies', website: 'kpmg.nl', status: 'new' },
  { name: 'McKinsey Amsterdam', sector: 'Zakelijke dienstverlening', size: 'medium', employee_count: 500, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Strategisch adviesbureau', website: 'mckinsey.com/nl', status: 'new' },
  { name: 'BCG Amsterdam', sector: 'Zakelijke dienstverlening', size: 'medium', employee_count: 350, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Strategisch adviesbureau', website: 'bcg.com', status: 'new' },
  { name: 'Randstad', sector: 'Zakelijke dienstverlening', size: 'enterprise', employee_count: 38000, city: 'Diemen', province: 'Noord-Holland', is_enterprise: true, description: 'HR-dienstverlening', website: 'randstad.nl', status: 'new' },
  { name: 'Brunel', sector: 'Zakelijke dienstverlening', size: 'large', employee_count: 12000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Detachering specialisten', website: 'brunel.nl', status: 'new' },
  { name: 'Yacht', sector: 'Zakelijke dienstverlening', size: 'large', employee_count: 2500, city: 'Diemen', province: 'Noord-Holland', is_enterprise: true, description: 'Professionals detachering', website: 'yacht.nl', status: 'new' },
  { name: 'Hays Nederland', sector: 'Zakelijke dienstverlening', size: 'medium', employee_count: 450, city: 'Amsterdam', province: 'Noord-Holland', description: 'Recruitment', website: 'hays.nl', status: 'new' },

  // EDUCATION
  { name: 'Universiteit van Amsterdam', sector: 'Onderwijs', size: 'enterprise', employee_count: 8000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, is_government: true, description: 'Grootste universiteit van NL', website: 'uva.nl', status: 'new' },
  { name: 'TU Delft', sector: 'Onderwijs', size: 'large', employee_count: 6000, city: 'Delft', province: 'Zuid-Holland', is_enterprise: true, is_government: true, is_tech: true, description: 'Technische universiteit', website: 'tudelft.nl', status: 'new' },
  { name: 'Universiteit Utrecht', sector: 'Onderwijs', size: 'large', employee_count: 7000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, is_government: true, description: 'Universiteit', website: 'uu.nl', status: 'new' },
  { name: 'Erasmus Universiteit', sector: 'Onderwijs', size: 'large', employee_count: 4500, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, is_government: true, description: 'Universiteit', website: 'eur.nl', status: 'new' },
  { name: 'TU Eindhoven', sector: 'Onderwijs', size: 'large', employee_count: 4000, city: 'Eindhoven', province: 'Noord-Brabant', is_enterprise: true, is_government: true, is_tech: true, description: 'Technische universiteit', website: 'tue.nl', status: 'new' },
  { name: 'Leiden University', sector: 'Onderwijs', size: 'large', employee_count: 6000, city: 'Leiden', province: 'Zuid-Holland', is_enterprise: true, is_government: true, description: 'Oudste universiteit van NL', website: 'universiteitleiden.nl', status: 'new' },
  { name: 'Hogeschool van Amsterdam', sector: 'Onderwijs', size: 'large', employee_count: 4000, city: 'Amsterdam', province: 'Noord-Holland', is_government: true, description: 'Hoger beroepsonderwijs', website: 'hva.nl', status: 'new' },
  { name: 'Hogeschool Rotterdam', sector: 'Onderwijs', size: 'large', employee_count: 3500, city: 'Rotterdam', province: 'Zuid-Holland', is_government: true, description: 'Hoger beroepsonderwijs', website: 'hogeschoolrotterdam.nl', status: 'new' },
  { name: 'Fontys Hogescholen', sector: 'Onderwijs', size: 'large', employee_count: 4500, city: 'Eindhoven', province: 'Noord-Brabant', is_government: true, description: 'Grootste hogeschool van NL', website: 'fontys.nl', status: 'new' },
  { name: 'Saxion', sector: 'Onderwijs', size: 'large', employee_count: 3000, city: 'Enschede', province: 'Overijssel', is_government: true, description: 'Hoger beroepsonderwijs', website: 'saxion.nl', status: 'new' },

  // CONSTRUCTION & REAL ESTATE
  { name: 'BAM', sector: 'Bouw & Vastgoed', size: 'enterprise', employee_count: 20000, city: 'Bunnik', province: 'Utrecht', is_enterprise: true, description: 'Bouw- en infrabedrijf', website: 'bam.com', status: 'new' },
  { name: 'VolkerWessels', sector: 'Bouw & Vastgoed', size: 'enterprise', employee_count: 17000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Bouwconcern', website: 'volkerwessels.com', status: 'new' },
  { name: 'Heijmans', sector: 'Bouw & Vastgoed', size: 'large', employee_count: 5000, city: 'Rosmalen', province: 'Noord-Brabant', is_enterprise: true, description: 'Bouw en vastgoed', website: 'heijmans.nl', status: 'new' },
  { name: 'CBRE Nederland', sector: 'Bouw & Vastgoed', size: 'medium', employee_count: 700, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Vastgoeddienstverlener', website: 'cbre.nl', status: 'new' },
  { name: 'JLL Nederland', sector: 'Bouw & Vastgoed', size: 'medium', employee_count: 400, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Vastgoeddienstverlener', website: 'jll.nl', status: 'new' },
  { name: 'Dura Vermeer', sector: 'Bouw & Vastgoed', size: 'large', employee_count: 3000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Bouwbedrijf', website: 'duravermeer.nl', status: 'new' },
  { name: 'TBI Holdings', sector: 'Bouw & Vastgoed', size: 'large', employee_count: 6000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Bouw en techniek', website: 'tbi.nl', status: 'new' },
  { name: 'Van Wijnen', sector: 'Bouw & Vastgoed', size: 'large', employee_count: 2500, city: 'Baarn', province: 'Utrecht', is_enterprise: true, description: 'Bouwbedrijf', website: 'vanwijnen.nl', status: 'new' },

  // RETAIL
  { name: 'Ahold Delhaize', sector: 'Retail & E-commerce', size: 'enterprise', employee_count: 150000, city: 'Zaandam', province: 'Noord-Holland', is_enterprise: true, description: 'Supermarkten (Albert Heijn)', website: 'aholddelhaize.com', status: 'new' },
  { name: 'Jumbo Supermarkten', sector: 'Retail & E-commerce', size: 'enterprise', employee_count: 100000, city: 'Veghel', province: 'Noord-Brabant', is_enterprise: true, description: 'Supermarktketen', website: 'jumbo.com', status: 'new' },
  { name: 'HEMA', sector: 'Retail & E-commerce', size: 'large', employee_count: 10000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Warenhuisketen', website: 'hema.nl', status: 'new' },
  { name: 'Action', sector: 'Retail & E-commerce', size: 'enterprise', employee_count: 65000, city: 'Zwaagdijk-Oost', province: 'Noord-Holland', is_enterprise: true, description: 'Discount retailer', website: 'action.com', status: 'new' },
  { name: 'IKEA Nederland', sector: 'Retail & E-commerce', size: 'large', employee_count: 7000, city: 'Amsterdam', province: 'Noord-Holland', is_enterprise: true, description: 'Meubelen en woonaccessoires', website: 'ikea.nl', status: 'new' },
  { name: 'MediaMarkt Nederland', sector: 'Retail & E-commerce', size: 'large', employee_count: 3000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, description: 'Consumentenelektronica', website: 'mediamarkt.nl', status: 'new' },

  // TELECOM
  { name: 'KPN', sector: 'ICT & Technologie', size: 'enterprise', employee_count: 10000, city: 'Rotterdam', province: 'Zuid-Holland', is_enterprise: true, is_tech: true, description: 'Telecombedrijf', website: 'kpn.com', status: 'new' },
  { name: 'VodafoneZiggo', sector: 'ICT & Technologie', size: 'enterprise', employee_count: 8000, city: 'Utrecht', province: 'Utrecht', is_enterprise: true, is_tech: true, description: 'Telecom en kabel', website: 'vodafoneziggo.nl', status: 'new' },
  { name: 'T-Mobile Nederland', sector: 'ICT & Technologie', size: 'large', employee_count: 3000, city: 'Den Haag', province: 'Zuid-Holland', is_enterprise: true, is_tech: true, description: 'Mobiele telecom', website: 't-mobile.nl', status: 'new' },

  // Additional medium/small companies for variety
  { name: 'Picnic', sector: 'Retail & E-commerce', size: 'large', employee_count: 15000, city: 'Duivendrecht', province: 'Noord-Holland', is_tech: true, is_enterprise: true, description: 'Online supermarkt', website: 'picnic.app', status: 'new' },
  { name: 'Bunq', sector: 'Financiële dienstverlening', size: 'medium', employee_count: 800, city: 'Amsterdam', province: 'Noord-Holland', is_tech: true, description: 'Digitale bank', website: 'bunq.com', status: 'new' },
  { name: 'Mollie', sector: 'ICT & Technologie', size: 'medium', employee_count: 750, city: 'Amsterdam', province: 'Noord-Holland', is_tech: true, description: 'Payment service provider', website: 'mollie.com', status: 'new' },
  { name: 'MessageBird', sector: 'ICT & Technologie', size: 'medium', employee_count: 600, city: 'Amsterdam', province: 'Noord-Holland', is_tech: true, description: 'Cloud communicatie', website: 'messagebird.com', status: 'new' },
  { name: 'Elastic', sector: 'ICT & Technologie', size: 'medium', employee_count: 300, city: 'Amsterdam', province: 'Noord-Holland', is_tech: true, description: 'Search en analytics', website: 'elastic.co', status: 'new' },
  { name: 'GitLab', sector: 'ICT & Technologie', size: 'medium', employee_count: 200, city: 'Amsterdam', province: 'Noord-Holland', is_tech: true, description: 'DevOps platform', website: 'gitlab.com', status: 'new' },
  { name: 'Miro', sector: 'ICT & Technologie', size: 'medium', employee_count: 400, city: 'Amsterdam', province: 'Noord-Holland', is_tech: true, description: 'Collaboration platform', website: 'miro.com', status: 'new' },
  { name: 'WeTransfer', sector: 'ICT & Technologie', size: 'medium', employee_count: 300, city: 'Amsterdam', province: 'Noord-Holland', is_tech: true, description: 'File transfer service', website: 'wetransfer.com', status: 'new' },
  { name: 'Bynder', sector: 'ICT & Technologie', size: 'medium', employee_count: 500, city: 'Amsterdam', province: 'Noord-Holland', is_tech: true, description: 'Digital asset management', website: 'bynder.com', status: 'new' },
  { name: 'Sendcloud', sector: 'ICT & Technologie', size: 'medium', employee_count: 400, city: 'Eindhoven', province: 'Noord-Brabant', is_tech: true, description: 'Shipping platform', website: 'sendcloud.nl', status: 'new' },
];
